# Generated by Django 5.1.4 on 2026-08-07 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Alt başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Aktivite',
                'verbose_name_plural': 'Aktiviteler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('activity_type', models.CharField(choices=[('run', 'Koşu'), ('yoga', 'Yoga'), ('hike', 'Doğa Yürüyüşü')], default='run', max_length=20, verbose_name='Aktivite türü')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('location', models.CharField(max_length=200, verbose_name='Buluşma noktası')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç zamanı')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Mesafe (km)')),
                ('level', models.CharField(blank=True, help_text='ör. Tüm seviyeler, Orta, İleri', max_length=100, verbose_name='Seviye')),
                ('participant_count', models.PositiveIntegerField(default=0, verbose_name='Katılımcı sayısı')),
                ('is_weekly', models.BooleanField(default=False, verbose_name='Haftalık tekrar')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
            ],
            options={
                'verbose_name': 'SSS',
                'verbose_name_plural': 'SSS',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='ör. 200+', max_length=20, verbose_name='Rakam')),
                ('key', models.CharField(help_text='ör. Topluluk', max_length=60, verbose_name='Etiket')),
                ('text', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'İstatistik',
                'verbose_name_plural': 'İstatistikler',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Görsel')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='community.event')),
            ],
            options={
                'verbose_name': 'Galeri görseli',
                'verbose_name_plural': 'Galeri',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
