# Generated by Django 5.1.4 on 2026-09-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_profile_commentlike_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='activity_type',
            field=models.CharField(choices=[('run', 'Koşu'), ('yoga', 'Yoga & Pilates'), ('hike', 'Doğa Yürüyüşü'), ('bike', 'Bisiklet'), ('orienteering', 'Oryantiring')], default='run', max_length=20, verbose_name='Aktivite türü'),
        ),
    ]
